/*
Landscape omnikeeper REST API

Testing UsageStatsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okclient

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_okclient_UsageStatsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test UsageStatsApiService UsageStatsFetch", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var version string

        resp, httpRes, err := apiClient.UsageStatsApi.UsageStatsFetch(context.Background(), version).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
