/*
Landscape omnikeeper REST API

Testing MetadataApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okclient

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_okclient_MetadataApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test MetadataApiService MetadataGetMetadata", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var context string

        resp, httpRes, err := apiClient.MetadataApi.MetadataGetMetadata(context.Background(), context).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test MetadataApiService MetadataGetServiceDocument", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var context string

        resp, httpRes, err := apiClient.MetadataApi.MetadataGetServiceDocument(context.Background(), context).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
