/*
Landscape omnikeeper REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package okclient

import (
	"encoding/json"
)

// LayerDTO struct for LayerDTO
type LayerDTO struct {
	Id string `json:"id"`
	Description string `json:"description"`
}

// NewLayerDTO instantiates a new LayerDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLayerDTO(id string, description string) *LayerDTO {
	this := LayerDTO{}
	this.Id = id
	this.Description = description
	return &this
}

// NewLayerDTOWithDefaults instantiates a new LayerDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLayerDTOWithDefaults() *LayerDTO {
	this := LayerDTO{}
	return &this
}

// GetId returns the Id field value
func (o *LayerDTO) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LayerDTO) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LayerDTO) SetId(v string) {
	o.Id = v
}

// GetDescription returns the Description field value
func (o *LayerDTO) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *LayerDTO) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *LayerDTO) SetDescription(v string) {
	o.Description = v
}

func (o LayerDTO) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableLayerDTO struct {
	value *LayerDTO
	isSet bool
}

func (v NullableLayerDTO) Get() *LayerDTO {
	return v.value
}

func (v *NullableLayerDTO) Set(val *LayerDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableLayerDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableLayerDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLayerDTO(val *LayerDTO) *NullableLayerDTO {
	return &NullableLayerDTO{value: val, isSet: true}
}

func (v NullableLayerDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLayerDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


