/*
Landscape omnikeeper REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package okclient

import (
	"encoding/json"
)

// InboundIDMethodByTemporaryCIID struct for InboundIDMethodByTemporaryCIID
type InboundIDMethodByTemporaryCIID struct {
	TempID *string `json:"tempID,omitempty"`
}

// NewInboundIDMethodByTemporaryCIID instantiates a new InboundIDMethodByTemporaryCIID object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInboundIDMethodByTemporaryCIID(type_ string) *InboundIDMethodByTemporaryCIID {
	this := InboundIDMethodByTemporaryCIID{}
	this.Type = type_
	return &this
}

// NewInboundIDMethodByTemporaryCIIDWithDefaults instantiates a new InboundIDMethodByTemporaryCIID object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInboundIDMethodByTemporaryCIIDWithDefaults() *InboundIDMethodByTemporaryCIID {
	this := InboundIDMethodByTemporaryCIID{}
	return &this
}

// GetTempID returns the TempID field value if set, zero value otherwise.
func (o *InboundIDMethodByTemporaryCIID) GetTempID() string {
	if o == nil || o.TempID == nil {
		var ret string
		return ret
	}
	return *o.TempID
}

// GetTempIDOk returns a tuple with the TempID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InboundIDMethodByTemporaryCIID) GetTempIDOk() (*string, bool) {
	if o == nil || o.TempID == nil {
		return nil, false
	}
	return o.TempID, true
}

// HasTempID returns a boolean if a field has been set.
func (o *InboundIDMethodByTemporaryCIID) HasTempID() bool {
	if o != nil && o.TempID != nil {
		return true
	}

	return false
}

// SetTempID gets a reference to the given string and assigns it to the TempID field.
func (o *InboundIDMethodByTemporaryCIID) SetTempID(v string) {
	o.TempID = &v
}

func (o InboundIDMethodByTemporaryCIID) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TempID != nil {
		toSerialize["tempID"] = o.TempID
	}
	return json.Marshal(toSerialize)
}

type NullableInboundIDMethodByTemporaryCIID struct {
	value *InboundIDMethodByTemporaryCIID
	isSet bool
}

func (v NullableInboundIDMethodByTemporaryCIID) Get() *InboundIDMethodByTemporaryCIID {
	return v.value
}

func (v *NullableInboundIDMethodByTemporaryCIID) Set(val *InboundIDMethodByTemporaryCIID) {
	v.value = val
	v.isSet = true
}

func (v NullableInboundIDMethodByTemporaryCIID) IsSet() bool {
	return v.isSet
}

func (v *NullableInboundIDMethodByTemporaryCIID) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInboundIDMethodByTemporaryCIID(val *InboundIDMethodByTemporaryCIID) *NullableInboundIDMethodByTemporaryCIID {
	return &NullableInboundIDMethodByTemporaryCIID{value: val, isSet: true}
}

func (v NullableInboundIDMethodByTemporaryCIID) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInboundIDMethodByTemporaryCIID) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


